language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    cargo build &&
    rustdoc src/lib.rs --crate-name sgp4 -o ./target/doc -L dependency=./target/debug -L dependency=./target/debug/deps --html-in-header=./docs/header_imports.html &&
    echo '<meta http-equiv=refresh content=0;url=sgp4/index.html>' > target/doc/index.html &&
    cd target/doc/ &&
    git init &&
    git config user.name "Travis CI" &&
    git config user.email "travisbot@example.com" &&
    git add . &&
    git commit -m "Travis Deploy to GitHub Pages" &&
    git push --force --quiet "https://${GH_TOKEN}@github.com/natronics/rust-sgp4.git" master:gh-pages > /dev/null 2>&1
